### ISSUE TITLE
enviroment hint und hintf sind nicht mehr definiert

### ISSUE THREAD

**Issue by reyabo** [wunderlich/edu#108]
Bei der Verwendung der Umgebung hint und hintf erhalten beim Kompilieren die Fehlermedlung, dass beide Umgebungen nicht mehr definiert seien. 

Absicht oder einfach eine fehlerhafte Installation von mir??

**Comment by wunderlich** [comment]
Also bei mir funktioniert es. Ich habe ja vor einiger Zeit alle Mathematik-Inhalte in das Package [edumath](https://github.com/wunderlich/edumath) ausgelagert, um _edu_ zu entschlacken. Das funktioniert bisher ganz gut, gibt aber noch diverse kleinere Probleme. Man kann das Package einfach als Option laden, sofern man ihm selbst wiederum keine Optionen übergeben möchte (sonst verwendet man `\usepackage`). Ein `\documentclass[edumath]{edu}` ermöglicht es mir, `hint` und `hintf` zu benutzen.

**Comment by reyabo** [comment]
Oh, natürlich. Daran hatte ich nicht mehr gedacht.
Danke

**Comment by wunderlich** [comment]
Sehr gut. Das sind die besten Probleme … :-)
