### ISSUE TITLE
Kein Footer in transparency mode

### ISSUE THREAD

**Issue by reyabo** [wunderlich/edu#87]

**Comment by wunderlich** [comment]
Danke für den Hinweis! Ich habe mich bewusst dazu entschieden, im transparency-Modus die Fußzeile zu deaktivieren:

```[latex]
  \bool_if:NT \g_edu_transparency_bool {
    \keys_set:nn {edu}{footer=false}
```

https://github.com/wunderlich/edu/blob/84fc2af9314f63620b889ffab2f3b38e2aca5732/edu.tex#L5063-L5064

 Hintergrund:
1. Erstellt man meistens einseitige Folien -- eine Fußzeile wird hinfällig.
2. Ist mir im Alltag immer wieder aufgefallen, dass auf Folien jeder Zentimeter Platz hilfreich ist.

Was meinst du @reyabo?

**Comment by reyabo** [comment]
Habs mir fast schon gedacht, wollte aber gewissheit haben :)

**Comment by wunderlich** [comment]
Ich habe mir noch einmal Gedanken gemacht. In letzter Zeit hatte ich immer wieder den Fall, dass die Fußzeile zumindest nicht gestört hätte. Es wäre wohl doch besser, wenn man sie zumindest wieder aktivieren könnte.
