### ISSUE TITLE
\res makro setzt Nummerierung von \multiexearray*-environment fort

### ISSUE THREAD

**Issue by reyabo** [wunderlich/edu#89]
Andere Umgebungen habe ich noch nicht getestet.
Der Aufwand den Counter manuell zurückzusetzen ist zwar nicht groß, aber manchmal vergisst man es einfach :-)

**Comment by wunderlich** [comment]
`\res` ist eigentlich dazu gedacht, z. B. in ein Arbeitsblatt direkt Lösungen zu ergänzen. Dann kann man ein Arbeitsblatt für die Schüler und ein Lösungsblatt erstellen. Hier ein Beispiel:

# showresults=false (default)
```[latex]
\documentclass[]{edu}

\begin{document}
  \exe{Erste Aufgabe}
  
  \begin{multiexelist}
    \item $\sqrt{36} = \res{6}$
    \item $\sqrt{49} = \res{7}$
  \end{multiexelist}
\end{document}
```

![res-1](https://cloud.githubusercontent.com/assets/4471366/19035255/b8daca18-8968-11e6-9431-3243be2c4411.png)

# showresults=true
```[latex]
\documentclass[showresults]{edu}

\begin{document}
  \exe{Erste Aufgabe}
  
  \begin{multiexelist}
    \item $\sqrt{36} = \res{6}$
    \item $\sqrt{49} = \res{7}$
  \end{multiexelist}
\end{document}
```
![res-2](https://cloud.githubusercontent.com/assets/4471366/19035296/f62f0942-8968-11e6-9aef-70bbd2d473dc.png)

Für ausführliche Lösungen stehen `\sol`, `\subsol` etc. zur Verfügung, die analog zu `\exe`, `\subexe` etc. arbeiten und die Counter der untergeordneten Aufgabenebenen (insb. `\multiexe*`) automatisch zurücksetzen.
