### ISSUE TITLE
\usepackage{verse} führt zu fehlermeldung

### ISSUE THREAD

**Issue by reyabo** [wunderlich/edu#94]
Die Verwendung des Package verse (Darstellung von Gedichten) führt zur folgenden Fehlermeldung. Command \theHpoemline already defined.
Scheinbar kollidieren da zwei Packete miteinander.

**Comment by wunderlich** [comment]
Es scheint ein Problem mit der doppelten Belegung von `\theHpoemline` bei der Verwendung von `verse` und `hyperref` (welches in `edu` standardäßig geladen wird) zu geben:

http://tex.stackexchange.com/a/239231/60539

Versuche mal folgenden Workaround zum Einbinden von `verse` (aus obigem Beitrag entnommen):

```
\let\orignewcommand\newcommand  % store the original \newcommand
\let\newcommand\providecommand  % make \newcommand behave like \providecommand
\RequirePackage{verse}
\let\newcommand\orignewcommand  % use the original `\newcommand` in future
\makeatletter
% Use the original definition from verse.sty
\renewcommand*{\theHpoemline}{\arabic{verse@envctr}.\arabic{poemline}}
\makeatother
```
Langfristig sollte `verse` durch eine Option vor `hyperref` eingebunden werden können.

**Comment by reyabo** [comment]
Danke für die schnelle Antwort :)

**Comment by wunderlich** [comment]
Habe gerade einen Patch commited. Es gibt jetzt eine Option `usepackageverse`. Mit ihr kannst du `verse` optional laden. In meinem Testdokument hat es geklappt. Teste es bitte mal, @reyabo.

**Comment by reyabo** [comment]
option muss innerhalb \documentclass aktiviert?
z.B. \documentclass[usepackageverse]{edu}

**Comment by wunderlich** [comment]
Beim Aufruf von `\documentclass`, also genau so, wie du es gemacht hast.

**Comment by reyabo** [comment]
Also ich bekomm es momentan nicht zum Laufen. Wenn ich die Option benutzt kommt nach wie vor dieselbe Fehlermeldung. Vllt liegt es aber auch an meinem Set-Up innerhalb der Datei. Kann erst nächste WE nochmal nen Blick drauf werfen, hab nämlich am Freitag Lehrprobe und deswegen wenig Zeit :-/

**Comment by wunderlich** [comment]
Du hast dir schon die neuste Version aus GitHub geholt? :-) Bei mir kommt die dann nicht mehr. Aber jetzt erst mal viel Erfolg bei der Lehrprobe. Melde dich einfach, wenn du Zeit hast!
